version: '3.8'

networks:
  jupy-network:
    

services:

  jupy-frontend:
    container_name: jupy-frontend
    build:
      context: ./jupy-frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - jupy-network

  jupy-backend:
    container_name: jupy-backend
    build:
      context: ./jupy-backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - NB_UID=1000
      - NB_GID=1000
      - NB_USER=jupyter
      - NB_GROUP=jupyter
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
      - CHOWN_EXTRA='/app'
    command: ["/opt/conda/envs/jupy-canvas/bin/jupyter", "server","--config=./jupyter_server_config.py",  "--ip=0.0.0.0", "--port=8888", "--allow-root"]
    depends_on:
      - jupy-frontend
    networks:
      - jupy-network


