version: '3.8'

networks:
  jupy-network:

services:
  jupy-frontend:
    image: "diegobugmann/jupy-canvas:jc-fe"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - jupy-network

  jupy-backend:
    image: "diegobugmann/jupy-canvas:jc-be"
    ports:
      - "8888:8888"
    volumes:
      - './Workspace:/app/Workspace'
    environment:
      - NB_UID=1000
      - NB_GID=1000
      - NB_USER=jupyter
      - NB_GROUP=jupyter
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
      - CHOWN_EXTRA='/app'
    command: ["/opt/conda/envs/jupy-canvas/bin/jupyter", "server", "--config=./server_config_docker.py", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
    networks:
      - jupy-network

  jupy-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf' # Map your custom Nginx configuration
    networks:
      - jupy-network
    depends_on:
      - jupy-frontend
      - jupy-backend

